language: ruby
env:
  - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom --server -Dcext.enabled=false -Xcompile.invokedynamic=false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - jruby-9.1.10.0
